# Etapa de build
FROM python:3.13-slim as builder

WORKDIR /app

# Instalar herramientas de compilación
RUN apt-get update && apt-get install -y \
    gcc \
    libc6-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir --user -r requirements.txt



# Etapa final
FROM python:3.13-slim

WORKDIR /app

# Instalar iproute2 para tc y libpcap para scapy
RUN apt-get update && apt-get install -y \
    iproute2 \
    libpcap0.8 \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /root/.local /root/.local

COPY . .

EXPOSE 11111

ENV PATH=/root/.local/bin:$PATH

CMD ["python", "-m", "uvicorn", "NetJemAPI:app", "--host", "0.0.0.0", "--port", "11111"]
